### ISSUE TITLE
Double row header

### ISSUE THREAD

**Issue by altrisi** [IrisShaders/irisshaders.github.io#12]
Since at some point, the website header is using two rows instead of one, when the content definitely fits in one, taking space from the main image or content. I'm supposing this is not intended. Same happens in the rest of pages.

![imagen](https://user-images.githubusercontent.com/17107132/122030879-741dd000-cdce-11eb-81a9-9a40d6400712.png)

Using Firefox if that matters

**Comment by maxigator** [comment]
it's an error look at the console

**Comment by maxigator** [comment]
i just commented a fix

**Comment by altrisi** [comment]
Is it intended that now the second row appears for half a second and then gets repositioned correctly?

**Comment by maxigator** [comment]
not really but it's the time the lang file loads

**Comment by thedocruby** [comment]
Resolved

**Comment by altrisi** [comment]
> 
> 
> not really but it's the time the lang file loads

But if with the language being the same it can be adjusted, why can't it be adjusted by default and resized if it doesn't fit? Can't see why it should depend on that.

Well whatever.
