### ISSUE TITLE
Selection Outline Not Displayed/Visible in Iris 1.17

### ISSUE THREAD

**Issue by LunaSeashell00** [IrisShaders/irisshaders.github.io#28]
Repro steps:
- Launch Iris 1.17 stand alone installation
- Enter any world
- Enable shaders: BSL or Complementary (latest dev versions, all default settings)
Expected: Default black selection outline should appear where crosshair is pointing
Observed: No selection outline at all
Note: This could be an issue with other shaders too, only tested using BSL and Comp at this point]

**Comment by thedocruby** [comment]
This issue pertains to the mod itself. I will refer you to the GitHub page for the mod (this is the website github):

https://github.com/IrisShaders/Iris
