### ISSUE TITLE
Box border dissappears randomly

### ISSUE THREAD

**Issue by jedenastka** [IrisShaders/irisshaders.github.io#39]
Right border on one of the "Why Iris?" boxes sometimes dissappears. Can be "fixed" by zooming in/out or opening dev tools.

Browser: `Chromium 90.0.4430.212 built on Debian 11.0, running on Debian 11.0` (confirmed to also be broken on the same version of Google Chrome)

![Screenshot_20210619_142247](https://user-images.githubusercontent.com/33988779/122642276-e01f7180-d109-11eb-8a49-d38fb5a8b778.png)
![Screenshot_20210619_142256](https://user-images.githubusercontent.com/33988779/122642277-e1509e80-d109-11eb-88d5-5b6505a0edaf.png)

**Comment by maxigator** [comment]
It only disappears when changing the window size

**Comment by maxigator** [comment]
found a (weird) fix could you test it? 
[my branch](https://git.maximeurban.fr/irisshaders.github.io/)

**Comment by jedenastka** [comment]
> found a (weird) fix could you test it?
> [my branch](https://git.maximeurban.fr/irisshaders.github.io/)

It now doesn't disappear, but is thinner (by a few pixels, but still noticable) than the rest.

![image](https://user-images.githubusercontent.com/33988779/122652678-3e674700-d140-11eb-9dfd-d825df4c61f9.png)

**Comment by maxigator** [comment]
yes, it's a math problem bc sometimes it's 0.5px and the browser just picks 0

**Comment by jedenastka** [comment]
> yes, it's a math problem bc sometimes it's 0.5px and the browser just picks 0

So it's impossible to fix?
