### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by salad-byte2** [IrisShaders/irisshaders.github.io#52]
I would like salad

**Comment by salad-byte2** [comment]
nvm

**Comment by salad-byte2** [comment]
donut better

**Comment by salad-byte2** [comment]
How do i delete an issue.. the donut god is never gonna forgive me..

**Comment by DragonEggBedrockBreaking** [comment]
I don’t think youths creator delete an issue, but the owner of a repository can delete issues.
